jwt:
  secret: "j-)a<w.*<bsysyA9=CM*N)q9S\7U^s_8s["


server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/seoul_restaurant
    password: 1111
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  security:
    user:
      name: a
      password: 1
